<h1>Introduccion a arrays de Numpy
<h6>8/31/22

In [1]:
#importando Numpy a Python
import numpy as np

In [2]:
#es para hacer lista
numpy_zeros= np.zeros(6)
numpy_zeros

array([0., 0., 0., 0., 0., 0.])

<h5>Lista no es igual a Lista de Numpy

In [3]:
#Generando una matriz de ceros
numpy_matriz= np.zeros((3,5))
numpy_matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
#invierte la matriz de (3,5) a (5,3)
numpy_matriz.transpose()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#Slicing

In [6]:
x=list(range(10))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
#Slicing con listas
x=list(range(10))
x[0:4]
x[0:5]

[0, 1, 2, 3, 4]

In [8]:
#Numpys Arrays
x=np.array((range(10)))
x[0:4]
x[0:5]

array([0, 1, 2, 3, 4])

In [11]:
#Operaciones matemáticas a Matrices
#dimesion de a = 6
a = np.array([1,2,3,4,5,6])
#dimension de b = 5
b = np.array([10,20,30,40,50,60])

In [10]:
a+b

array([11, 22, 33, 44, 55, 66])

In [21]:
matrizA=np.zeros((3,3))
matrizB=np.zeros((1,3))

In [22]:
matrizA+matrizB

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])